Feature: label support for directories
SAP/terraform-provider-btp pull request #221
Opened 2023-06-23 13:08 UTC by lechnerc77

## Purpose

* This PR introduces label support for directories

## Does this introduce a breaking change?

```
[ ] Yes
[X] No
```

## Pull Request Type

What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[X] Feature
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test

* Test the code via unit tests:

```
go test ./...
```
* Alternative: Build Terraform provider and create a directory with or without labels 

## What to Check

Verify that the following are valid

* Directory gets created as configured

## Other Information

An additional test for labels cannot be created, dependency to PR #219

2023-06-23 13:26 UTC, v0lkc commented on internal/btpcli/facade_accounts_directory_test.go
> +				"labels":        "null",
I think in this case, labels shouldn't be set at all

2023-06-23 13:28 UTC, v0lkc requested changes

2023-06-23 13:28 UTC, v0lkc commented on internal/btpcli/facade_accounts_directory_test.go
> +				"labels":        "null",
```suggestion
```

I think in this case it's better to not send the labels to the cli backend.

2023-06-23 13:28 UTC, v0lkc commented on internal/btpcli/facade_accounts_directory_test.go
> +				"labels":        "null",
same here

2023-06-23 15:06 UTC, lechnerc77 commented on internal/btpcli/facade_accounts_directory_test.go
> +				"labels":        "null",
Fixed

2023-06-23 15:06 UTC, lechnerc77 commented on internal/btpcli/facade_accounts_directory_test.go
> +				"labels":        "null",
Fixed

2023-06-26 07:46 UTC, v0lkc approved these changes

2023-06-26 07:46 UTC, merged