fix(service-instance): support parameters resolution
SAP/terraform-provider-btp pull request #666
Opened 2024-01-19 09:59 UTC by v0lkc

## Purpose

* ...

## Does this introduce a breaking change?

```
[ ] Yes
[ ] No
```

## Pull Request Type

What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test

* Test the code via automated test

```bash
go test ./...
```

* Additional test steps

```
...
```

## What to Check

Verify that the following are valid:

* Automated tests are executed successfully

* ...

## Other Information

## Checklist for reviewer

The following organizational tasks must be completed before merging this PR:

* [ ] The PR is assigned to the Terraform project and a status is set (typically "in review").
* [ ] The PR has the matching labels assigned to it.
* [ ] The PR has a milestone assigned to it.
* [ ] If the PR closes an issue, the issue is referenced.
* [ ] Possible follow-up items are created and linked.

2024-01-19 11:48 UTC, lechnerc77 reviewed
@v0lkc the enhancement opens up to fetch the service instance with parameters. However the import logic is not enhanced. 
The discussed solution was to check in the import if the parameters could be read and if not to throw an error that import is not possible.

2024-01-24 09:59 UTC, lechnerc77 commented
Fixture drift is okay, as a new recording was necessary to reflect the changed HTTP requests for the service instance resource and data source.

2024-01-24 10:00 UTC, lechnerc77 commented
Inclusive language checks cannot be solved on our end as caused by platform API responses

2024-01-26 10:28 UTC, kuntzed requested changes

2024-01-26 10:28 UTC, kuntzed commented on internal/btpcli/facade_services_instance.go
>  		"parameters": "false",
Since the reason to introduce the doGet is to send two requests, one with parameters=false and one with parameters=true, I would prefer to move this into doGet (see below).

2024-01-26 10:28 UTC, kuntzed commented on internal/btpcli/facade_services_instance.go
> +
Let's add

params["parameters"] = "false"

here for symmetry and readability.

2024-01-26 10:28 UTC, kuntzed commented on internal/btpcli/facade_services_instance_test.go
> +	subaccountId := "59cd458e-e66e-4b60-b6d8-8f219379f9a5"
Is this a real id? In the facade tests it should not matter. Probably does not even need to be a GUID.
Or why did the id change?

2024-01-26 11:15 UTC, lechnerc77 commented on internal/btpcli/facade_services_instance.go
>  		"parameters": "false",
Moved the setting of params to the `doGet` function with corresponding comments

2024-01-26 11:15 UTC, lechnerc77 commented on internal/btpcli/facade_services_instance.go
> +
Good point - adjusted

2024-01-26 11:15 UTC, lechnerc77 commented on internal/btpcli/facade_services_instance_test.go
> +	subaccountId := "59cd458e-e66e-4b60-b6d8-8f219379f9a5"
That was some glitch during recording, changed it back to original value

2024-01-26 11:39 UTC, kuntzed approved these changes
Thank you very much for providing this workaround.

2024-01-26 11:39 UTC, merged