feat: Resource to create roles
SAP/terraform-provider-btp pull request #858
Opened 2024-07-19 08:29 UTC by ANUGRAHG

## Purpose
Added role-specific resources in the provider for directory, global account, and subaccount.
This PR will resolve issue #841 

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type

What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[x] Feature
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test

* Test the code via automated test

```bash
go test ./...
```

* Additional test steps

```
...
```

## What to Check

Verify that the following are valid:

* Automated tests are executed successfully

* ...

## Other Information

## Checklist for reviewer

The following organizational tasks must be completed before merging this PR:

* [ ] The PR is assigned to the Terraform project and a status is set (typically "in review").
* [ ] The PR has the matching labels assigned to it.
* [ ] The PR has a milestone assigned to it.
* [ ] If the PR closes an issue, the issue is referenced.
* [ ] Possible follow-up items are created and linked.

2024-07-19 09:00 UTC, lechnerc77 requested changes
The tests for the `UPDATE` and `IMPORT` operations should be added to the test cases to ensure that we cover all available operations in the tests.

In addition, I think the test cases need to be re-recorded as they currently run into errors.

2024-07-19 09:00 UTC, lechnerc77 commented on internal/provider/resource_directory_role_test.go
> +	t.Run("happy path", func(t *testing.T) {
The test should also comprise an update and an import to check all available operations.

2024-07-19 09:00 UTC, lechnerc77 commented on internal/provider/resource_globalaccount_role_test.go
> +		resource.Test(t, resource.TestCase{
The test should also comprise an update and an import to check all available operations.

2024-07-19 09:00 UTC, lechnerc77 commented on internal/provider/resource_subaccount_role_test.go
> +		resource.Test(t, resource.TestCase{
The test should also comprise an update and an import to check all available operations.

2024-07-22 10:13 UTC, ANUGRAHG commented on internal/provider/resource_globalaccount_role_test.go
> +		resource.Test(t, resource.TestCase{
Added tests for import and update

2024-07-22 10:13 UTC, ANUGRAHG commented on internal/provider/resource_directory_role_test.go
> +	t.Run("happy path", func(t *testing.T) {
Done

2024-07-22 10:42 UTC, vipinvkmenon approved these changes

2024-07-22 10:45 UTC, lechnerc77 approved these changes
lgtm

2024-07-22 10:45 UTC, merged